variables:
  LC_ALL: C.UTF-8

stages:
  - test
  - deploy

.debian: &debian
  image: $CI_REGISTRY/knot/knot-resolver/ci/debian-buster:knot-3.0
  tags:
    - docker
    - linux
    - amd64

test:mypy:
  <<: *debian
  script:
    - ./ci/mypy-run.sh

test:flake8:
  <<: *debian
  script:
    - python3 -m flake8 --max-line-length=100 . && echo "OK, no flake8 errors detected"

test:pylint:
  <<: *debian
  script:
    - pip3 install -r requirements.txt
    - ./ci/pylint-run.sh

test:luacheck:
  <<: *debian
  script:
    - ./ci/luacheck-run.sh

# docs published to GitLab Pages: https://knot.pages.nic.cz/shotgun/
pages:
  image: $CI_REGISTRY/packaging/apkg/ci/python-current:apkg
  stage: deploy
  script:
    - mkdocs build
    - mv site public
  artifacts:
    paths:
      - public
  only:
     - tags
