variables:
  LC_ALL: C.UTF-8

stages:
  - test
  - deploy

.debian: &debian
  image: $CI_REGISTRY/knot/knot-resolver/ci/debian-11:knot-3.0
  tags:
    - docker
    - linux
    - amd64

black:
  image: docker.io/pyfound/black:latest
  tags:
    - docker
    - linux
    - amd64
  script:
    - black --check .

mypy:
  <<: *debian
  script:
    - ./ci/mypy-run.sh

pylint:
  <<: *debian
  script:
    - pip3 install -r requirements.txt
    - ./ci/pylint-run.sh

luacheck:
  <<: *debian
  script:
    - ./ci/luacheck-run.sh

docker:
  stage: deploy
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build --no-cache -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
  tags:
    - dind
  only:
     - tags
