variables:
  LC_ALL: C.UTF-8

stages:
  - test
  - deploy

.debian: &debian
  image: $CI_REGISTRY/knot/knot-resolver/ci/debian-buster:knot-3.0
  tags:
    - docker
    - linux
    - amd64

test:mypy:
  <<: *debian
  script:
    - ./ci/mypy-run.sh

test:flake8:
  <<: *debian
  script:
    - python3 -m flake8 --max-line-length=100 . && echo "OK, no flake8 errors detected"

test:pylint:
  <<: *debian
  script:
    - pip3 install -r requirements.txt
    - ./ci/pylint-run.sh

test:luacheck:
  <<: *debian
  script:
    - ./ci/luacheck-run.sh

docker:
  stage: deploy
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build --no-cache -t "shotgun:v$CI_COMMIT_TAG" .
    - docker push "shotgun:v$CI_COMMIT_TAG"
  tags:
    - dind
  only:
     - tags
