# Plain DNS over UDP traffic sender.
[traffic]

# DNS-over-UDP clients.
[traffic.UDP]
protocol = "udp"


[charts]

[charts.latency]
type = "latency"

[charts.response-rate]
type = "response-rate"

[charts.response-rate-rcodes]
type = "response-rate"
rcodes-above-pct = 0
