#!/usr/bin/env dnsjit

-- mark-frequent-queries.lua: limit measurements to most repetitive queries
--
-- Process PCAP prepared with extract-clients.lua,
-- where all packets have source port set to 53,
-- by changing the port of some packets from 53 to 52.
--
-- The least significant bit of the source port indicates,
-- whether the packet should be counted into measurements,
-- not affecting replaying the queries;
-- i.e. all queries are still sent, but only 53-origin ones' answers are counted.
--
-- This script sets the bit for the given percent of the most repetitive queries
-- and clears it for others.

local bit = require("bit")
local ffi = require("ffi")
local output = require("dnsjit.output.pcap").new()
local object = require("dnsjit.core.objects")
local dns = require("dnsjit.core.object.dns")
local label = require("dnsjit.core.object.dns.label")
local Q = require("dnsjit.core.object.dns.q")
local log = require("dnsjit.core.log").new("mark-frequent-queries.lua")
local getopt = require("dnsjit.lib.getopt").new({
	{ "r", "read", "", "input file to read", "?" },
	{ "w", "write", "", "output file to write (or /dev/null)", "?" },
	{ "p", "percents", 10.0, "percents of queries to be included in measurements", "?" },
})

local SNAPLEN = 66000

log:enable("all")

-- Parse arguments
local args = {}
getopt:parse()
args.read = getopt:val("r")
args.write = getopt:val("w")
args.percents = getopt:val("p")

-- Display help
if getopt:val("help") then
	getopt:usage()
	return
end

-- Check arguments
if args.percents < 0.0 or args.percents > 100.0 then
	log:fatal("percents must be between 0 and 100")
end

-- Set up input
local function open_input(file)
	local input = require("dnsjit.input.pcap").new()
	local layer = require("dnsjit.filter.layer").new()
	if args.read ~= "" then
		if input:open_offline(file) ~= 0 then
			log:fatal("failed to open input PCAP "..args.read)
		end
		log:notice("using input PCAP "..args.read)
	else
		getopt:usage()
		log:fatal("input must be specified, use -r")
	end
	layer:producer(input)
	return input, layer, layer:produce()
end
local input, layer, produce, pctx = open_input(args.read)

-- Set up output
if args.write == "" then
	log:fatal("output must be specified, use -w; use /dev/null if you want just counters")
elseif output:open(args.write, input:linktype(), input:snaplen()) ~= 0 then
	log:fatal("failed to open output PCAP "..args.write)
else
	log:notice("using output PCAP "..args.write)
end
local write, writectx = output:receive()

local obj_pcap_out = ffi.new("core_object_pcap_t")
obj_pcap_out.obj_type = object.PCAP

local bytes = ffi.new("uint8_t[?]", SNAPLEN)
obj_pcap_out.bytes = bytes

local function put_uint16_be(dst, offset, src)
	dst[offset] = bit.rshift(bit.band(src, 0xff00), 8)
	dst[offset + 1] = bit.band(src, 0xff)
end

local function check_output()
	if output:have_errors() then
		log:fatal("error writting to file %s", outfilename)
	end
end

local function get_qstr(obj_dns)
	if obj_dns:parse_header() ~= 0 then
		return
	end
	local labels = label.new(16)
	local q = Q.new()
	if obj_dns.qdcount == 1 then
		for n = 1, obj_dns.qdcount do
			if obj_dns:parse_q(q, labels, 16) ~= 0 then
				return
			end
			return dns.class_tostring(q.class) .. " " .. dns.type_tostring(q.type) .. " " .. label.tooffstr(obj_dns, labels, 16)
		end
	elseif obj_dns.qdcount == 0 then
		return
	else
		log:notice("queries with multiple questions not counted and marked as untracked");
	end
end

local obj, obj_pcap_in, obj_ip, obj_udp, obj_pl, obj_dns
local npacketsin = 0
local npacketserr = 0
local questions_cnts = {}
log:notice("counting same queries...")
while true do
	obj = produce(pctx)
	if obj == nil then break end
	npacketsin = npacketsin + 1

	obj_ip = obj:cast_to(object.IP6)
	obj_udp = obj:cast_to(object.UDP)
	obj_pl = obj:cast_to(object.PAYLOAD)
	obj_pcap = obj:cast_to(object.PCAP)
	obj_dns = dns.new(obj)
	if obj_ip == nil or obj_udp == nil or obj_pl == nil or obj_pcap == nil or obj_dns == nil then
		log:fatal('malformed packet found, only IPv6 UDP DNS queries generated by extract-clients.lua are supported');
	end

	local qstr = get_qstr(obj_dns)
	if qstr ~= nil then
		local cnt = questions_cnts[qstr]
		if cnt == nil then cnt = 0 end
		cnt = cnt + 1
		questions_cnts[qstr] = cnt
	else
		npacketserr = npacketserr + 1
	end

	if npacketsin % 100000 == 0 then
		log:notice("  " .. npacketsin .. " packets processed")
    collectgarbage()
	end
end
local nquestions = npacketsin - npacketserr

log:notice(string.format("  input packets:   %10d", npacketsin))
log:notice(string.format("  parsed packets:  %10d", nquestions))

local questions = {}
local nkeys = 0

for k,v in pairs(questions_cnts) do
  if v > 1 then
    table.insert(questions, { q = k, c = v })
  end
end
questions_cnts = nil
collectgarbage()

local function qcmp(q1, q2)
	return q1.c > q2.c
end
log:notice(string.format("  unique questions:%10d", #questions))
log:notice("sorting questions...")
table.sort(questions, qcmp)

for i=1, #questions do
	print(string.format("%10d  %s", questions[i].c, questions[i].q));
end

log:notice("choosing tracked questions...")
local tracked = {}
local nneeded = nquestions * args.percents / 100
local ntracked = 0
for i,v in ipairs(questions) do
	tracked[v.q] = true
	nneeded = nneeded - v.c
	ntracked = ntracked + 1
	if nneeded <= 0 then break end
end
if nneeded > 0 then
  log:warn("tracking all except single occurrences, possibly less than wanted")
end
log:notice(string.format("  tracked questions: %10d /%10d", ntracked, #questions))
questions = nil


local input, layer, produce, pctx = open_input(args.read)
log:notice("filtering packets...")

local npacketsout = 0
local npacketstracked = 0
while true do
	obj = produce(pctx)
	if obj == nil then break end

	obj_ip = obj:cast_to(object.IP6)
	obj_udp = obj:cast_to(object.UDP)
	obj_pl = obj:cast_to(object.PAYLOAD)
	obj_pcap = obj:cast_to(object.PCAP)
	obj_dns = dns.new(obj)
	if obj_ip == nil or obj_udp == nil or obj_pl == nil or obj_pcap == nil or obj_dns == nil then
		log:fatal('malformed packet found, only IPv6 UDP DNS queries generated by extract-clients.lua are supported');
	end

	ffi.copy(bytes, obj_pcap.bytes, obj_pcap.len)
	obj_pcap_out.ts = obj_pcap.ts;
	obj_pcap_out.len = obj_pcap.len
	obj_pcap_out.caplen = obj_pcap_out.len

	local qstr = get_qstr(obj_dns)
	if qstr ~= nil and tracked[qstr] ~= nil then
		put_uint16_be(bytes, 40, 0x0035)  -- normalized src port 53
		npacketstracked = npacketstracked + 1
	else
		put_uint16_be(bytes, 40, 0x0034)  -- normalized src port 52
	end

	-- check output state only every 10 000 packets - optimization
	if npacketsout % 10000 == 0 then
		check_output()
	end
	write(writectx, obj_pcap_out:uncast())
	npacketsout = npacketsout + 1
end

check_output()
output:close()

log:notice(string.format("  output packets:  %10d", npacketsout))
log:notice(string.format("  tracked packets: %10d", npacketstracked))

if npacketsin ~= npacketsout then
	log:fatal('input/output packets number mismatch')
end
